- name: Windows Harden (Collection Test)
  hosts: all

  tasks:

    - name: "Turn Windows Firewall On (Module)"
      win_firewall:
        state: enabled
        profile: Domain
      

    - name: "Turn Windows Firewall On (Collection)"
      community.windows.win_firewall:
        state: enabled
        profile: Domain

    - name: Win Ping
      win_ping:
      
     



   
